[hugoVersion]
[[imports]]
  path = "github.com/mattstratton/castanet/v2"
[[mounts]]
  source = 'assets'
  target = 'assets'
[[mounts]]
  disableWatch = true
  source = 'hugo_stats.json'
  target = 'assets/notwatching/hugo_stats.json'